_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch:
    value: 16
epochs:
    value: 100
imgsz:
    value: 640
